name: 🤖 Keepalive Ping

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update keepalive timestamp
        run: date +%Y-%m-%dT%H:%M:%S > .github/keepalive.txt

      - name: Commit keepalive timestamp
        run: |
          git config --global user.name "deloca-bot"
          git config --global user.email "actions@github.com"
          git add .github/keepalive.txt
          git commit -m "🤖 Keepalive ping" || echo "No changes to commit"

      - name: Push commit using PAT
        env:
          GH_TOKEN_PUSH: ${{ secrets.GH_TOKEN_PUSH }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN_PUSH}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
