name: 🤖 Keepalive Ping

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update keepalive timestamp
        run: |
          date +%Y-%m-%dT%H:%M:%S > .github/keepalive.txt

      - name: Commit changes
        run: |
          git config --global user.name "deloca-bot"
          git config --global user.email "actions@github.com"
          git add .github/keepalive.txt
          git commit -m "🤖 Keepalive ping" || echo "Nothing to commit"

      - name: Push changes with PAT
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN_PUSH }}@github.com/${{ github.repository }}.git HEAD:main
